name: Lint Code

on:
  pull_request:
    branches:
      - main

jobs:
  lint-code:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run linters
        run: poetry run invoke code.check
